# Generated by Django 5.0.2 on 2024-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_agency', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(verbose_name='story date'),
        ),
    ]
